spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    initialize: false
    initialization-mode: always
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  mustache:
    expose-session-attributes: true

  batch:
    initializer-schema: always

logging:
  level:
    org:
      springframework:
        security: debug

server:
  port: 8080